---
repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - name: remove whitespaces
        id: trailing-whitespace
      - name: add newline to end of files
        id: end-of-file-fixer
      - name: sort requiremtns.txt
        id: requirements-txt-fixer

  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - name: sort python imports
        id: isort

  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - name: re-format with black
        id: black
        language_version: python3

  - repo: https://github.com/pycqa/flake8
    rev: 5.0.4
    hooks:
      - name: check syntax with flake8
        id: flake8

  - repo: https://github.com/asottile/setup-cfg-fmt
    rev: v2.0.0
    hooks:
      - name: format setup.cfg
        id: setup-cfg-fmt
        args: [--include-version-classifiers]

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.27.1
    hooks:
      - name: check YAML format
        id: yamllint
